feat: add class-is module
ipfs/interface-datastore pull request #24
Opened 2018-10-04 10:02 UTC by vasco-santos

The `instance of` fails when using different versions of a module. This way, we end up with problems using this in other places, such as [js-ipfs/core/ipns/publisher.js#L93](https://github.com/ipfs/js-ipfs/blob/master/src/core/ipns/publisher.js#L93).

In the context of [js-ipfs/issues/1615](https://github.com/ipfs/js-ipfs/issues/1615)

2018-10-04 10:05 UTC, fsdiogo approved these changes
LGTM 👍

2018-10-07 16:08 UTC, daviddias approved these changes

2018-10-15 11:49 UTC, alanshaw approved these changes

2018-10-15 11:57 UTC, alanshaw requested changes
There are a number of occasions in this file where we're accessing the non-wrapped `Key` class:

These all need to be changed otherwise they create `Key` objects that don't have the '@ipfs/interface-datastore/key' symbol and so aren't considered to be instances of `Key` when used with `Key.isKey`.

2018-10-17 12:44 UTC, vasco-santos commented
@alanshaw just fixed your review. Thanks!

2018-10-17 13:11 UTC, alanshaw approved these changes

2018-10-22 17:13 UTC, diasdavid commented
@pgte can you drive this merge and get it released?

2018-10-23 08:54 UTC, pgte commented
@vasco-santos could you please rebase from master?

2018-10-23 08:55 UTC, pgte approved these changes
LGTM

2018-10-24 12:37 UTC, vasco-santos commented
Rebased @pgte !

2018-10-24 13:20 UTC, merged

2018-10-24 13:35 UTC, pgte commented
Landed on v0.6.0.